### ISSUE TITLE
Make MegaBot great (again)

### ISSUE THREAD

**Issue by aurxl** [aurxl/MegaBot#5]
## known issues (to be solved)
- [ ] Status when playing music:
    - [ ] #resume doesn't stop status timer 
    - [ ] Status is always global and public
 
## todo
- [x] adding queue for playing music 
- [ ] Bot should leave channel automatically after playing music (timer or when nobody is in channel)
- [ ] general update and redesign of functions and features (e.g. w2g, help etc.) 
- [ ] adding logging system

**Comment by aurxl** [comment]
#4
